Add QueryInsights and  support
GoogleCloudPlatform/k8s-config-connector pull request #2690
Opened 2024-09-13 03:03 UTC by nitashadhingra

### Change description

Fixes #

### Tests you have done

- [ ] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

2024-09-18 12:29 UTC, yuwenma commented
Hi @maqiuyujoyce , could you help @nitashadhingra  on this PR review?

2024-09-18 18:19 UTC, maqiuyujoyce reviewed
Hi @nitashadhingra , thank you for supporting the new feature in AlloyDBInstance.

Could you run `make ready-pr` locally and also ensure the updated tests pass locally (instructions: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/docs/archive/README.NewResourceFromTerraform.md#run-tests)?

I think you may also want to build KCC locally (step 11 inhttps://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/CONTRIBUTING.md#set-up-your-environment), apply the updated samples, and verify if the behavior of the fields that you set to `false` work as expected. The reason I asked for verification is that setting a field to `false` for a TF-based resource means deleting the field. So I'm concerned about it's behavior after being applied. If it doesn't align with the expectation, then we need to discuss about it.

2024-09-19 05:56 UTC, nitashadhingra commented on pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/fullalloydbinstance/update.yaml
> +    cpuCount: 2
right, i was testing for a change only in the observability config. will undo this

2024-09-19 05:56 UTC, nitashadhingra commented
> Hi @nitashadhingra , thank you for supporting the new feature in AlloyDBInstance.
> 
> Could you run `make ready-pr` locally and also ensure the updated tests pass locally (instructions: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/docs/archive/README.NewResourceFromTerraform.md#run-tests)?
> 
> I think you may also want to build KCC locally (step 11 in https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/CONTRIBUTING.md#set-up-your-environment), apply the updated samples, and verify if the behavior of the fields that you set to `false` work as expected. The reason I asked for verification is that setting a field to `false` for a TF-based resource means deleting the field. So I'm concerned about it's behavior after being applied. If it doesn't align with the expectation, then we need to discuss about it.

- fullalloydbinstance integration test passed: https://paste.googleplex.com/6287857661771776
- manually tested with the `samples/` directory create and update configs: https://pantheon.corp.google.com/alloydb/locations/us-central1/clusters/alloydbinstance-dep-primary/query-insights;duration=PT1H;sort_by=TOTAL_EXEC_TIME/executed?e=TraceAllCallsThroughColiseumLaunch::TraceAllCallsThroughColiseumEnabled&inv=1&invt=Abcg2w&mods=-logs_tg_prod&project=nitashadhingra-playground
- ran `make ready-pr`: https://paste.googleplex.com/6306384674291712

2024-09-19 18:44 UTC, maqiuyujoyce commented
> * fullalloydbinstance integration test passed: https://paste.googleplex.com/6287857661771776

Looks like what you pasted here is the test result for `fullalloydbcluster` instead. Do you have the test result for `fullalloydbinstance`?

> * manually tested with the `samples/` directory create and update configs: https://pantheon.corp.google.com/alloydb/locations/us-central1/clusters/alloydbinstance-dep-primary/query-insights;duration=PT1H;sort_by=TOTAL_EXEC_TIME/executed?e=TraceAllCallsThroughColiseumLaunch::TraceAllCallsThroughColiseumEnabled&inv=1&invt=Abcg2w&mods=-logs_tg_prod&project=nitashadhingra-playground

I think we should post internal links publicly and I don't have access to your project. Could you use screenshots or something else to show it?

> * ran `make ready-pr`: https://paste.googleplex.com/6306384674291712

Changes done by `make ready-pr` should be part of the PR. Could you update your PR with the `make ready-pr` result?

Please also ensure all the presubmit tests running in this PR pass. You should have access to the logs if you click `Details` for the corresponding test.

2024-09-24 19:04 UTC, 199201shubhamsahu requested changes
Can you also add the new `queryInsightsConfig` and `observabilityConfig` fields in the `secondary-instance` sample folder.

2024-09-26 06:59 UTC, nitashadhingra commented
> Can you also add the new `queryInsightsConfig` and `observabilityConfig` fields in the `secondary-instance` sample folder.

hi Shubham, these configs are not supported for secondary cluster and instances

2024-09-27 01:39 UTC, 199201shubhamsahu commented
> > Can you also add the new `queryInsightsConfig` and `observabilityConfig` fields in the `secondary-instance` sample folder.
> 
> hi Shubham, these configs are not supported for secondary cluster and instances
I see, in that case we don't need to add it here.

But let's ensure that there is some validation from the backend so that users see some error message if they set these fields for secondary instance when creating or updating the instance.

2024-10-03 18:40 UTC, maqiuyujoyce commented
Hi @nitashadhingra looks like you removed the changes made in the third_party folder, could you help me understand why?

The error from presubmit validations said that:
```
Error: Your commit "cdf53c5fea7c2d495daad38ab5b9876dbbea1221" includes changes both within and outside the
"third_party/github.com/hashicorp/terraform-provider-google-beta/" directory.
```

This means you need to change the original commit and split out any changes under `third_party/github.com/hashicorp/terraform-provider-google-beta/` into a separate commit.

2024-10-03 22:45 UTC, maqiuyujoyce commented
Besides, could you also fix the two failed alloydb test cases in Presubmit / tests-e2e-fixtures ?

2024-10-11 15:12 UTC, nitashadhingra commented
> Looks like what you pasted here is the test result for `fullalloydbcluster` instead. Do you have the test result for `fullalloydbinstance`?

Result for fullalloydbinsitance: https://paste.googleplex.com/6238184242675712

2024-10-12 02:54 UTC, maqiuyujoyce commented
Hi @nitashadhingra , it looks like the [Presubmit / validations (pull_request)](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/11283371294/job/31424804303?pr=2690) still failed with the following error:

```
Error: Your commit "abc839d551c112e8e3fac6775109b3606ece03a0" includes changes both within and outside the
"third_party/github.com/hashicorp/terraform-provider-google-beta/" directory.
Please ensure that changes made within this directory are grouped and
submitted as a separate, dedicated commit.
```

This validation basically checks whether any of the commit in this PR contains changes not only under `third_party/` but in files under other folders. To fix this, you need to revert commit abc839d551c112e8e3fac6775109b3606ece03a0, add changes under `third_party/` and create one commit, then add the rest changes, and create a second commit.

Looking at your commit history, commit cdf53c5fea7c2d495daad38ab5b9876dbbea1221 also has the same issue, so you'll need to revert commit cdf53c5fea7c2d495daad38ab5b9876dbbea1221 and split changes into separate commits following the same steps above.

2024-10-12 02:55 UTC, maqiuyujoyce commented
Alternatively, you can leverage the new PR #2883 to make additive changes there. That might be easier than cleaning up the commit history here.

2026-05-29 19:04 UTC, ldanielmadariaga commented
This item has been open for >12 months. As part of scheduled repository maintenance, this Issue/PR will be closed. If this is still a critical ask, please re-open and work with your Google Cloud Account team to prioritize it with GCP KCC Product Management.

2026-05-29 19:04 UTC, closed without merging